package jetbrain.mps.cryptoexchange.feedback;

/*Generated by MPS */

import jetbrains.mps.core.aspects.feedback.api.FeedbackAspect;
import org.jetbrains.annotations.NotNull;
import java.util.stream.Stream;
import jetbrains.mps.core.aspects.feedback.api.FeedbackPerConceptDescriptor;

public final class GeneratedFeedbackAspectFeedback implements FeedbackAspect {
  @NotNull
  @Override
  public Stream<FeedbackPerConceptDescriptor> getPerConceptDescriptors() {
    return Stream.of(new order_FeedbackFeedback(), new TransferRequest_FeedbackFeedback(), new account_FeedbackFeedback(), new TokenPair_FeedbackFeedback());
  }
}
