package jetbrain.mps.cryptoexchange.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_leverageType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_leverageType() {
    super(0x885932350df545d0L, 0xbc76936b0ff5f304L, 0x3b9502d85a84049eL, "leverageType", "r:984aa0d0-cdbe-4539-96fb-298ff1435c32(jetbrain.mps.cryptoexchange.structure)/4293340948022428830");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember__1x_0 = new EnumerationDescriptor.MemberDescriptor("_1x", "_1x", 0x3b9502d85a84049fL, "r:984aa0d0-cdbe-4539-96fb-298ff1435c32(jetbrain.mps.cryptoexchange.structure)/4293340948022428831");
  private final EnumerationDescriptor.MemberDescriptor myMember__2x_0 = new EnumerationDescriptor.MemberDescriptor("_2x", "_2x", 0x3b9502d85a8404a0L, "r:984aa0d0-cdbe-4539-96fb-298ff1435c32(jetbrain.mps.cryptoexchange.structure)/4293340948022428832");
  private final EnumerationDescriptor.MemberDescriptor myMember__5x_0 = new EnumerationDescriptor.MemberDescriptor("_5x", "_5x", 0x3b9502d85a8404a3L, "r:984aa0d0-cdbe-4539-96fb-298ff1435c32(jetbrain.mps.cryptoexchange.structure)/4293340948022428835");
  private final EnumerationDescriptor.MemberDescriptor myMember__10x_0 = new EnumerationDescriptor.MemberDescriptor("_10x", "_10x", 0x3b9502d85a8404a7L, "r:984aa0d0-cdbe-4539-96fb-298ff1435c32(jetbrain.mps.cryptoexchange.structure)/4293340948022428839");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x885932350df545d0L, 0xbc76936b0ff5f304L, 0x3b9502d85a84049eL, 0x3b9502d85a84049fL, 0x3b9502d85a8404a0L, 0x3b9502d85a8404a3L, 0x3b9502d85a8404a7L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember__1x_0, myMember__2x_0, myMember__5x_0, myMember__10x_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember__1x_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "_1x":
        return myMember__1x_0;
      case "_2x":
        return myMember__2x_0;
      case "_5x":
        return myMember__5x_0;
      case "_10x":
        return myMember__10x_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
