package jetbrain.mps.cryptoexchange.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_transferType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_transferType() {
    super(0x885932350df545d0L, 0xbc76936b0ff5f304L, 0x3b9502d85b032071L, "transferType", "r:984aa0d0-cdbe-4539-96fb-298ff1435c32(jetbrain.mps.cryptoexchange.structure)/4293340948030759025");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_IntraExchange_0 = new EnumerationDescriptor.MemberDescriptor("IntraExchange", "IntraExchange", 0x3b9502d85b032072L, "r:984aa0d0-cdbe-4539-96fb-298ff1435c32(jetbrain.mps.cryptoexchange.structure)/4293340948030759026");
  private final EnumerationDescriptor.MemberDescriptor myMember_ExtraExchange_0 = new EnumerationDescriptor.MemberDescriptor("ExtraExchange", "ExtraExchange", 0x3b9502d85b032073L, "r:984aa0d0-cdbe-4539-96fb-298ff1435c32(jetbrain.mps.cryptoexchange.structure)/4293340948030759027");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x885932350df545d0L, 0xbc76936b0ff5f304L, 0x3b9502d85b032071L, 0x3b9502d85b032072L, 0x3b9502d85b032073L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_IntraExchange_0, myMember_ExtraExchange_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "IntraExchange":
        return myMember_IntraExchange_0;
      case "ExtraExchange":
        return myMember_ExtraExchange_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
