package jetbrain.mps.cryptoexchange.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_AccountType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_AccountType() {
    super(0x885932350df545d0L, 0xbc76936b0ff5f304L, 0x4ae7a0d4d1aa575dL, "AccountType", "r:984aa0d0-cdbe-4539-96fb-298ff1435c32(jetbrain.mps.cryptoexchange.structure)/5397459514337941341");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Future_0 = new EnumerationDescriptor.MemberDescriptor("Future", "Future", 0x4ae7a0d4d1aa575eL, "r:984aa0d0-cdbe-4539-96fb-298ff1435c32(jetbrain.mps.cryptoexchange.structure)/5397459514337941342");
  private final EnumerationDescriptor.MemberDescriptor myMember_Margin_0 = new EnumerationDescriptor.MemberDescriptor("Margin", "Margin", 0x4ae7a0d4d1aa575fL, "r:984aa0d0-cdbe-4539-96fb-298ff1435c32(jetbrain.mps.cryptoexchange.structure)/5397459514337941343");
  private final EnumerationDescriptor.MemberDescriptor myMember_Spot_0 = new EnumerationDescriptor.MemberDescriptor("Spot", "Spot", 0x4ae7a0d4d1aa5762L, "r:984aa0d0-cdbe-4539-96fb-298ff1435c32(jetbrain.mps.cryptoexchange.structure)/5397459514337941346");
  private final EnumerationDescriptor.MemberDescriptor myMember_Saving_0 = new EnumerationDescriptor.MemberDescriptor("Saving", "Saving", 0x4ae7a0d4d1aa5766L, "r:984aa0d0-cdbe-4539-96fb-298ff1435c32(jetbrain.mps.cryptoexchange.structure)/5397459514337941350");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x885932350df545d0L, 0xbc76936b0ff5f304L, 0x4ae7a0d4d1aa575dL, 0x4ae7a0d4d1aa575eL, 0x4ae7a0d4d1aa575fL, 0x4ae7a0d4d1aa5762L, 0x4ae7a0d4d1aa5766L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Future_0, myMember_Margin_0, myMember_Spot_0, myMember_Saving_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Spot_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Future":
        return myMember_Future_0;
      case "Margin":
        return myMember_Margin_0;
      case "Spot":
        return myMember_Spot_0;
      case "Saving":
        return myMember_Saving_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
