package jetbrain.mps.cryptoexchange.actions;

/*Generated by MPS */

import jetbrains.mps.actions.descriptor.BaseActionAspectDescriptor;
import jetbrains.mps.openapi.actions.descriptor.ActionAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;

public class ActionAspectDescriptorImpl extends BaseActionAspectDescriptor implements ActionAspectDescriptor {
  private static final String LANGUAGE_FQ_NAME = "jetbrain.mps.cryptoexchange";

  @Override
  public Collection<NodeFactory> getFactories(SAbstractConcept concept) {
    if (LANGUAGE_FQ_NAME.equals(concept.getLanguage().getQualifiedName())) {
      switch (concept.getName()) {
        case "account":
          return Collections.<NodeFactory>singletonList(new AccountID.NodeFactory_4293340948023062197());
        case "order":
          return Collections.<NodeFactory>singletonList(new createNextID.NodeFactory_4213103153630464565());
        default:
      }
    }
    return Collections.<NodeFactory>emptyList();
  }

}
