package jetbrain.mps.cryptoexchange.actions;

/*Generated by MPS */

import jetbrains.mps.openapi.actions.descriptor.NodeFactory;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrain.mps.cryptoexchange.behavior.subsystem__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;

public class createNextID {
  public static class NodeFactory_4213103153630464565 implements NodeFactory {
    public void setup(SNode newNode, SNode sampleNode, SNode enclosingNode, int index, SModel model) {
      SPropertyOperations.assign(newNode, PROPS.ID$9Jt2, subsystem__BehaviorDescriptor.getNextOrderId_id3DRWJW9YzO_.invoke(SNodeOperations.cast(enclosingNode, CONCEPTS.subsystem$US)));
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty ID$9Jt2 = MetaAdapterFactory.getProperty(0x885932350df545d0L, 0xbc76936b0ff5f304L, 0x2a868524b103cefcL, 0x2a868524b103ceffL, "ID");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept subsystem$US = MetaAdapterFactory.getConcept(0x885932350df545d0L, 0xbc76936b0ff5f304L, 0x151908d59864d166L, "jetbrain.mps.cryptoexchange.structure.subsystem");
  }
}
